export enum SecuritiesType {
    LAND_BUILDING_SECURITY,
    APARTMENT_SECURITY ,
    VEHICLE_SECURITY ,
    PROPERTY_AND_MACHINERY_SECURITY ,
    FIXED_DEPOSIT_RECEIPT ,
    SHARE_SECURITY ,
    EDUCATION_CERTIFICATE ,
    MARKETABLE_SECURITIES ,
    GOLD_AND_SILVER ,
    PERSONAL_GUARANTOR ,
    PROMOTER_SHARE ,
    CORPORATE,
}
