image: node:10

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - rm ./package-lock.json
    - npm install --quiet
    - ./node_modules/@angular/cli/bin/ng build --prod
  artifacts:
    paths:
      - dist/