image: node:10

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
#    - rm ./package-lock.json
    - npm install --quiet
    - node --max_old_space_size=8192  ./node_modules/@angular/cli/bin/ng build --prod
  artifacts:
    paths:
      - dist/
  only:
    - master
    - merge_requests
