export class RetailLoanNameConstant {
    static EDUCATION_LOAN_COMBINED = 'EDUCATION LOAN COMBINED';
    static PERSONAL_OVERDRAFT_COMBINED = 'PERSONAL OVERDRAFT COMBINED';
    static PERSONAL_LOAN_COMBINED = 'PERSONAL LOAN COMBINED';
    static MORTGAGE_LOAN_COMBINED = 'MORTGAGE LOAN COMBINED';
    static AUTO_LOAN_COMBINED = 'AUTO LOAN COMBINED';
    static HOME_LOAN_COMBINED = 'HOME LOAN COMBINED';
    static NABIL_SAHAYATRI_KARJA = 'NABIL SAHAYATRI KARJA';
    static SHARE_LOAN_DEMAND_COMBINED = 'SHARE LOAN DEMAND COMBINED';
    static NABIL_SHARE_LOAN_POD_COMBINED = 'NABIL SHARE LOAN POD COMBINED';
    static PERSONAL_OVERDRAFT_WITHOUT_COLLATERAL_COMBINED = 'PERSONAL OVERDRAFT WITHOUT COLLATERAL COMBINED';
}
