export class LoanNameConstant {
    static CUSTOMER_ACCEPTANCE_FOR_TIME_LETTER_OF_CREDIT = 'CUSTOMER ACCEPTANCE FOR TIME LETTER OF CREDIT';
    static IRREVOCABLE_LETTER_OF_CREDIT_FACILITY = 'IRREVOCABLE LETTER OF CREDIT FACILITY';
}
