import {SiteVisit} from '../../admin/modal/siteVisit';
import {Financial} from './financial';
import {Security} from './security';
import {GuarantorDetail} from './guarantor-detail';
import {Insurance} from '../../admin/modal/insurance';
import {CustomerGeneralDocument} from '../../customer/model/customerGeneralDocument';
import {CustomerGroup} from '../../admin/modal/customer-group';
import {CreditRiskGradingAlpha} from '../../admin/modal/CreditRiskGradingAlpha';
import {CreditRiskGrading} from '../../admin/modal/creditRiskGrading';
import {Branch} from '../../admin/modal/branch';
import {CustomerLoanFlag} from '../../../@core/model/customer-loan-flag';
import {CreditRiskGradingGamma} from '../../admin/modal/creditRiskGradingGamma';
import {Cicl, CiclArray} from '../../admin/modal/cicl';
import {IncomeFromAccount} from '../../admin/modal/incomeFromAccount';
import {NetTradingAssets} from '../../admin/modal/NetTradingAssets';
import {CreditChecklistGeneral} from './creditChecklistGeneral';
import {MicroLoanSynopsis} from './micro-loan-synopsis';
import {MicroBaselRiskExposure} from './micro-basel-risk-exposure';

export class CustomerInfoData {
    id: number;
    name: string;
    idType: any;
    idNumber: string;
    customerType: any;
    idRegDate: any;
    contactNo: string;
    email: string;
    idRegPlace: string;
    associateId: number;
    isBlacklist: boolean;
    branch: Branch;
    siteVisit: SiteVisit;
    financial: Financial;
    creditRiskGradingAlpha: CreditRiskGradingAlpha;
    creditRiskGrading: CreditRiskGrading;
    crgGamma: CreditRiskGradingGamma;
    version: number;
    security: Security;
    shareSecurity;
    guarantors: GuarantorDetail;
    insurance: Array<Insurance>;
    customerGeneralDocuments: Array<CustomerGeneralDocument>;
    customerGroup: CustomerGroup;
    profilePic: string;
    loanFlags: Array<CustomerLoanFlag>;
    cicl: CiclArray;
    incomeFromAccount: IncomeFromAccount;
    netTradingAssets: NetTradingAssets;
    bankingRelationship: string;
    creditChecklist: CreditChecklistGeneral;
    obligor: string;
    customerCode: string;
    subSectorDetailCode: string;
    nepData: string;
    synopsisCreditworthiness: MicroLoanSynopsis;
    microBaselRiskExposure: MicroBaselRiskExposure;
}
