import {Province} from '../../admin/modal/province';
import {District} from '../../admin/modal/district';
import {MunicipalityVdc} from '../../admin/modal/municipality_VDC';

export class Guarantor {
    id: number;
    version: number;
    name: string;
    province: Province;
    district: District;
    municipalities: MunicipalityVdc;
    provinceTemporary: Province;
    districtTemporary: District;
    municipalitiesTemporary: MunicipalityVdc;
    citizenNumber: string;
    issuedYear: Date;
    issuedPlace: string;
    contactNumber: string;
    fatherName: string;
    grandFatherName: string;
    relationship: string;
    docPath: string;
    netWorth: number;
    consentOfLegalHeirs: boolean;
    streetName: string;
    permanentAddressLine1: string;
    permanentAddressLine2: string;
    temporaryAddressLine1: string;
    temporaryAddressLine2: string;
    wardNumber: number;
    streetNameTemporary: string;
    wardNumberTemporary: number;
    dateOfBirth: Date;
    motherName: string;
    spouseName: string;
    fatherInLaw: string;
    profession: string;
    background: string;
    guarantorLegalDocumentAddress: string;
}
