export class NabilConstants {
    static AUTO_LOAN = 'AUTO_LOAN';
    static EDUCATIONAL = 'EDUCATIONAL';
    static PERSONAL_LOAN = 'PERSONAL_LOAN';
    static PERSONAL_OVERDRAFT = 'PERSONAL_OVERDRAFT';
    static PERSONAL_OVERDRAFT_WITHOUT_COLLATERAL = 'PERSONAL_OVERDRAFT_WITHOUT_COLLATERAL';
    static PERSONAL_LOAN_AND_PERSONAL_OVERDRAFT = 'PERSONAL_LOAN_AND_PERSONAL_OVERDRAFT';
    static HOME_LOAN = 'HOME_LOAN';
    static MORTAGE_LOAN = 'MORTAGE_LOAN';
    static SHARE_LOAN = 'SHARE_LOAN';
    static NABIL_SAHAYATRI_KARJA = 'NABIL_SAHAYATRI_KARJA';
    static KISAN_KARJA_SUBSIDY = 'KISAN_KARJA_SUBSIDY';
    static UDYAMSIL_KARJA_SUBSIDY = 'UDYAMSIL_KARJA_SUBSIDY';
    static INTEREST_SUBSIDY_SANCTION_LETTER = 'INTEREST_SUBSIDY_SANCTION_LETTER';
    static DDSL_WITHOUT_SUBSIDY = 'DDSL_WITHOUT_SUBSIDY';
    static CLASS_A = 'CLASS_A';
    static COMBINED_LETTER = 'COMBINED_LETTER';
}
