import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';

@Component({
    selector: 'app-section2-loan-type',
    templateUrl: './section2-loan-type.component.html',
    styleUrls: ['./section2-loan-type.component.scss']
})
export class Section2LoanTypeComponent implements OnInit {
    form: FormGroup;

    constructor(private formBuilder: FormBuilder,
    ) {
    }

    ngOnInit() {
        this.buildForm();
    }

    buildForm() {
        this.form = this.formBuilder.group({
            // Irrevocable letter of credit facility
            SNOfParentLimitIrrevocable: [undefined],
            loanAmountIrrevocable: [undefined],
            loanAmountInWordIrrevocable: [undefined],
            marginInPercentageIrrevocable: [undefined],
            commissionRateIrrevocable: [undefined],
            commissionAmountIrrevocable: [undefined],
            commissionRateForFirstQuarterIrrevocable: [undefined],
            commissionRateForOtherQuarterIrrevocable: [undefined],
            loanExpiryDateIrrevocable: [undefined],
            loanExpiryDateIrrevocable2: [undefined],
            // Customer Acceptance for Time Letter of Credit
            SNOfParentLimitTimeLetter: [undefined],
            loanAmountTimeLetter: [undefined],
            loanAmountInWordTimeLetter: [undefined],
            marginInPercentageTimeLetter: [undefined],
            commissionRateQuarterlyTimeLetter: [undefined],
            commissionAmountTimeLetter: [undefined],
            loanExpiryDateTimeLetter: [undefined],
            loanExpiryDateTimeLetter2: [undefined],
            // Import Bills Discounting
            loanDaysBillsDiscounting: [undefined],
            loanDaysBillsDiscountingInEng: [undefined],
            SNOfParentLimitBillsDiscounting: [undefined],
            loanAmountBillsDiscounting: [undefined],
            loanAmountInWordBillsDiscounting: [undefined],
            marginInPercentageBillsDiscounting: [undefined],
            loanExpiryDateBillsDiscounting: [undefined],
            // Import Loan/ Trust Receipt Loan
            loanDaysLoanTrust: [undefined],
            loanDaysLoanTrustInEng: [undefined],
            SNOfParentLimitLoanTrust: [undefined],
            loanAmountLoanTrust: [undefined],
            loanAmountInWordLoanTrust: [undefined],
            drawingPowerLoanTrust: [undefined],
            baseRateLoanTrust: [undefined],
            premiumRateLoanTrust: [undefined],
            interestRateLoanTrust: [undefined],
            totalInterestRateLoanTrust: [undefined],
            remainDaysLoanTrust: [undefined],
            loanExpiryDateLoanTrust: [undefined],
            // Revolving/One off basis Short Term Loan
            loanDaysShortTermLoan: [undefined],
            loanDaysShortTermLoanInEng: [undefined],
            SNOfParentLimitShortTermLoan: [undefined],
            loanMonthsShortTermLoan: [undefined],
            loanMonthsShortTermLoanInEng: [undefined],
            loanAmountShortTermLoan: [undefined],
            loanAmountInWordShortTermLoan: [undefined],
            ARDaysShortTermLoan: [undefined],
            drawingPowerShortTermLoan: [undefined],
            baseRateShortTermLoan: [undefined],
            premiumRateShortTermLoan: [undefined],
            interestRateShortTermLoan: [undefined],
            totalInterestRateShortTermLoan: [undefined],
            remainDaysShortTermLoan: [undefined],
            loanExpiryDateShortTermLoan: [undefined],
            // Demand Loan for working capital
            SNOfParentLimitDemandLoan: [undefined],
            loanAmountDemandLoan: [undefined],
            LoanAmountInWordDemandLoan: [undefined],
            ARDaysDemandLoan: [undefined],
            drawingPowerDemandLoan: [undefined],
            baseRateDemandLoan: [undefined],
            premiumRateDemandLoan: [undefined],
            interestRateDemandLoan: [undefined],
            totalInterestRateDemandLoan: [undefined],
            loanExpiryDateDemandLoan: [undefined],
            // Pre-Export Loan
            SNOfParentLimitPreExport: [undefined],
            loanAmountPreExport: [undefined],
            loanAmountInWordPreExport: [undefined],
            drawingPower1PreExport: [undefined],
            drawingPower2PreExport: [undefined],
            sulkaPreExport: [undefined],
            interestRatePreExport: [undefined],
            loanExpiryDatePreExport: [undefined],
            // Documentary Bill Purchase/Negotiation
            SNOfParentLimitDocumentaryBill: [undefined],
            loanAmountDocumentaryBill: [undefined],
            loanAmountInWordDocumentaryBill: [undefined],
            marginInPercentageDocumentaryBill: [undefined],
            drawingPowerDocumentaryBill: [undefined],
            InterestRateDocumentaryBill: [undefined],
            loanPaymentDocumentaryBill: [undefined],
            loanExpiryDateDocumentaryBill: [undefined],
            // Overdraft Loan for Working Capital requirement
            loanAmountOverdraftLoan: [undefined],
            loanAmountInWordOverdraftLoan: [undefined],
            ARDaysOverdraftLoan: [undefined],
            drawingPowerOverdraftLoan: [undefined],
            baseRateOverdraftLoan: [undefined],
            premiumRateOverdraftLoan: [undefined],
            interestRateOverdraftLoan: [undefined],
            totalInterestRateOverdraftLoan: [undefined],
            loanExpiryDateOverdraftLoan: [undefined],
            // Mortgage Overdraft/ Other Overdraft/ Equity Mortgaged Overdraft
            loanAmountMortgageOverdraft: [undefined],
            loanAmountInWordMortgageOverdraft: [undefined],
            drawingPowerMortgageOverdraft: [undefined],
            baseRateMortgageOverdraft: [undefined],
            premiumRateMortgageOverdraft: [undefined],
            interestRateMortgageOverdraft: [undefined],
            totalInterestRateMortgageOverdraft: [undefined],
            loanExpiryDateMortgageOverdraft: [undefined],
            // Overdraft Facility against Fixed Deposit/ Lien on Deposit Account
            nameOfFacilityOverdraftFacility: [undefined],
            nameOfFacilityOverdraftFacilityInEng: [undefined],
            loanAmountOverdraftFacility: [undefined],
            loanAmountInWordOverdraftFacility: [undefined],
            nameOfFDHolderOverdraftFacility: [undefined],
            FDAmountOverdraftFacility: [undefined],
            nameOfBankOverdraftFacility: [undefined],
            nameOfDepositorOverdraftFacility: [undefined],
            accountTypeOverdraftFacility: [undefined],
            accountNoOverdraftFacility: [undefined],
            amountOverdraftFacility: [undefined],
            drawingPowerOverdraftFacility: [undefined],
            additionalPremiumOverdraftFacility: [undefined],
            couponInterestRateOverdraftFacility: [undefined],
            baseRateOverdraftFacility: [undefined],
            premiumRateOverdraftFacility: [undefined],
            interestRateOverdraftFacility: [undefined],
            loanExpiryDateOverdraftFacility: [undefined],
            // Overdraft Facility against Bond
            nameOfFacilityAgainstBond: [undefined],
            nameOfFacilityAgainstBondInEng: [undefined],
            loanAmountAgainstBond: [undefined],
            loanAmountInWordAgainstBond: [undefined],
            ownerNameAgainstBond: [undefined],
            bondAmountAgainstBond: [undefined],
            bondTypeAgainstBond: [undefined],
            totalInterestRateAgainstBond: [undefined],
            baseRateAgainstBond: [undefined],
            premiumRateAgainstBond: [undefined],
            interestRateAgainstBond: [undefined],
            loanExpiryDateAgainstBond: [undefined],
            // Bridge Gap Loan
            SNOfParentLimitBridgeGap: [undefined],
            loanAmountBridgeGap: [undefined],
            loanAmountInWordBridgeGap: [undefined],
            baseRateBridgeGap: [undefined],
            premiumRateBridgeGap: [undefined],
            interestRateBridgeGap: [undefined],
            totalInterestRateBridgeGap: [undefined],
            // Term Loan to/for
            SNOfParentLimitVehicleLoan: [undefined],
            purposeLoanVehicleLoan: [undefined],
            purposeLoanVehicleLoanInEng: [undefined],
            loanAmountVehicleLoan: [undefined],
            loanAmountInWordVehicleLoan: [undefined],
            // For New EMI Term Loan
            newEMIBaseRateVehicleLoan: [undefined],
            newEMIPremiumRateVehicleLoan: [undefined],
            newEMIInterestRateVehicleLoan: [undefined],
            newEMIAmountVehicleLoan: [undefined],
            newEMIAmountInWordVehicleLoan: [undefined],
            newEMINoOfInstallmentVehicleLoan: [undefined],
            newEMISubsequentVehicleLoan: [undefined],
            newEMILoanPurposeVehicleLoan: [undefined],
            newEMIServiceChargeVehicleLoan: [undefined],
            newEMILoanTenureVehicleLoan: [undefined],
            // For EMI Term Loan at the time of Annual Review of other credit limits
            annualEMIBaseRateVehicleLoan: [undefined],
            annualEMIPremiumRateVehicleLoan: [undefined],
            annualEMIInterestRateVehicleLoan: [undefined],
            annualEMIAmountVehicleLoan: [undefined],
            annualEMIAmountInWordVehicleLoan: [undefined],
            annualEMILoanExpiryDateVehicleLoan: [undefined],
            // For New Installment Basis Term Loan
            newInstallmentBaseRateVehicleLoan: [undefined],
            newInstallmentPremiumRateVehicleLoan: [undefined],
            newInstallmentInterestRateVehicleLoan: [undefined],
            newInstallmentTotalInterestRateVehicleLoan: [undefined],
            newInstallmentLoanTenureVehicleLoan: [undefined],
            newInstallmentPaymentAmountVehicleLoan: [undefined],
            newInstallmentPaymentAmountInWordVehicleLoan: [undefined],
            newInstallmentNoOfPaymentVehicleLoan: [undefined],
            newInstallmentPaymentTypeVehicleLoan: [undefined],
            newInstallmentPaymentDurationVehicleLoan: [undefined],
            newInstallmentLoanPurposeVehicleLoan: [undefined],
            newInstallmentServiceChargeVehicleLoan: [undefined],
            // For Installment Basis Term Loan at the time of Annual Review of other credit limits
            annualInstallmentBaseRateVehicleLoan: [undefined],
            annualInstallmentPremiumRateVehicleLoan: [undefined],
            annualInstallmentInterestRateVehicleLoan: [undefined],
            annualInstallmentTotalInterestRateVehicleLoan: [undefined],
            annualInstallmentPaymentAmountVehicleLoan: [undefined],
            annualInstallmentPaymentAmountInWordVehicleLoan: [undefined],
            annualInstallmentNoOfPaymentVehicleLoan: [undefined],
            annualInstallmentPaymentTypeVehicleLoan: [undefined],
            annualInstallmentLoanExpiryDateVehicleLoan: [undefined],
            // Mortgage Term Loan / Equity Mortgage Term Loan
            SNOfParentLimitMortgageTerm: [undefined],
            loanAmountMortgageTerm: [undefined],
            loanAmountInWordMortgageTerm: [undefined],
            drawingPowerMortgageTerm: [undefined],
            // For New EMI Term Loan
            newEMIBaseRateMortgageTerm: [undefined],
            newEMIPremiumRateMortgageTerm: [undefined],
            newEMIInterestRateMortgageTerm: [undefined],
            newEMIAmountMortgageTerm: [undefined],
            newEMIAmountInWordMortgageTerm: [undefined],
            newEMINoOfInstallmentMortgageTerm: [undefined],
            newEMIAutoPopulateMortgageTerm: [undefined],
            newEMILoanPurposeMortgageTerm: [undefined],
            newEMIServiceChargeMortgageTerm: [undefined],
            newEMILoanTenureMortgageTerm: [undefined],
            // For EMI Term Loan at the time of Annual Review of other credit limits
            annualEMIBaseRateMortgageTerm: [undefined],
            annualEMIPremiumRateMortgageTerm: [undefined],
            annualEMIInterestRateMortgageTerm: [undefined],
            annualEMIAmountMortgageTerm: [undefined],
            annualEMIAmountInWordMortgageTerm: [undefined],
            annualEMILoanExpiryDateMortgageTerm: [undefined],
            // For New Installment Basis Term Loan
            newInstallmentBaseRateMortgageTerm: [undefined],
            newInstallmentPremiumRateMortgageTerm: [undefined],
            newInstallmentInterestRateMortgageTerm: [undefined],
            newInstallmentTotalInterestRateMortgageTerm: [undefined],
            newInstallmentLoanTenureMortgageTerm: [undefined],
            newInstallmentPaymentAmountMortgageTerm: [undefined],
            newInstallmentPaymentAmountInWordMortgageTerm: [undefined],
            newInstallmentNoOfPaymentMortgageTerm: [undefined],
            newInstallmentPaymentTypeMortgageTerm: [undefined],
            newInstallmentPaymentDurationMortgageTerm: [undefined],
            newInstallmentLoanPurposeMortgageTerm: [undefined],
            newInstallmentServiceChargeMortgageTerm: [undefined],
            // For Installment Basis Term Loan at the time of Annual Review of other credit limits
            annualInstallmentBaseRateMortgageTerm: [undefined],
            annualInstallmentPremiumRateMortgageTerm: [undefined],
            annualInstallmentInterestRateMortgageTerm: [undefined],
            annualInstallmentTotalInterestRateMortgageTerm: [undefined],
            annualInstallmentPaymentAmountMortgageTerm: [undefined],
            annualInstallmentPaymentAmountInWordMortgageTerm: [undefined],
            annualInstallmentNoOfPaymentMortgageTerm: [undefined],
            annualInstallmentPaymentTypeMortgageTerm: [undefined],
            annualInstallmentLoanExpiryDateMortgageTerm: [undefined],
            annualInstallmentDrawingPowerMortgageTerm: [undefined],
            annualInstallmentDrawingPowerMortgageTerm1: [undefined],
            // Auto Loan
            SNOfParentLimitAutoLoan: [undefined],
            loanAmountAutoLoan: [undefined],
            loanAmountInWordAutoLoan: [undefined],
            // For New EMI Term Loan
            newEMIDrawingPowerAutoLoan: [undefined],
            newEMIBaseRateAutoLoan: [undefined],
            newEMIPremiumRateAutoLoan: [undefined],
            newEMIInterestRateAutoLoan: [undefined],
            newEMIAmountAutoLoan: [undefined],
            newEMIAmountInWordAutoLoan: [undefined],
            newEMINoOfInstallmentAutoLoan: [undefined],
            newEMIAutoPopulateAutoLoan: [undefined],
            newEMILoanPurposeAutoLoan: [undefined],
            newEMIServiceChargeAutoLoan: [undefined],
            newEMILoanTenureAutoLoan: [undefined],
            // For EMI Term Loan at the time of Annual Review of other credit limits
            annualEMIBaseRateAutoLoan: [undefined],
            annualEMIPremiumRateAutoLoan: [undefined],
            annualEMIInterestRateAutoLoan: [undefined],
            annualEMIAmountAutoLoan: [undefined],
            annualEMIAmountInWordAutoLoan: [undefined],
            annualEMILoanExpiryDateAutoLoan: [undefined],
            // For New Installment Basis Term Loan
            newInstallmentBaseRateAutoLoan: [undefined],
            newInstallmentPremiumRateAutoLoan: [undefined],
            newInstallmentInterestRateAutoLoan: [undefined],
            newInstallmentLoanTenureAutoLoan: [undefined],
            newInstallmentPaymentAmountAutoLoan: [undefined],
            newInstallmentPaymentAmountInWordAutoLoan: [undefined],
            newInstallmentNoOfPaymentAutoLoan: [undefined],
            newInstallmentPaymentTypeAutoLoan: [undefined],
            newInstallmentPaymentDurationAutoLoan: [undefined],
            newInstallmentLoanPurposeAutoLoan: [undefined],
            newInstallmentServiceChargeAutoLoan: [undefined],
            // For Installment Basis Term Loan at the time of Annual Review of other credit limits
            annualInstallmentBaseRateAutoLoan: [undefined],
            annualInstallmentPremiumRateAutoLoan: [undefined],
            annualInstallmentInterestRateAutoLoan: [undefined],
            annualInstallmentPaymentAmountAutoLoan: [undefined],
            annualInstallmentPaymentAmountInWordAutoLoan: [undefined],
            annualInstallmentNoOfPaymentAutoLoan: [undefined],
            annualInstallmentPaymentTypeAutoLoan: [undefined],
            annualInstallmentLoanExpiryDateAutoLoan: [undefined],
            annualInstallmentDrawingPowerAutoLoan: [undefined],
            annualInstallmentNameOfDealerAutoLoan: [undefined],
            // Bank Guarantee
            SNOfParentLimitBankGuarantee: [undefined],
            loanAmountBankGuarantee: [undefined],
            loanAmountInWordBankGuarantee: [undefined],
            nameOfBankBankGuarantee: [undefined],
            marginInPercentageBankGuarantee: [undefined],
            commission1BankGuarantee: [undefined],
            commission1BankGuarantee1: [undefined],
            serviceChargeBankGuarantee: [undefined],
            minimumServiceChargeBankGuarantee1: [undefined],
            commission2BankGuarantee: [undefined],
            commission2BankGuarantee1: [undefined],
            minimumServiceChargeBankGuarantee2: [undefined],
            loanExpiryDateBankGuarantee1: [undefined],
            // Bills Purchase
            SNOfParentLimitBillsPurchase: [undefined],
            loanAmountBillsPurchase: [undefined],
            loanAmountInWordBillsPurchase: [undefined],
            marginInPercentageBillsPurchase: [undefined],
            commissionBillsPurchase: [undefined],
            commissionAmountBillsPurchase: [undefined],
            loanExpiryDateBillsPurchase: [undefined],
            // other Input Fields
            SNOfFacility: [undefined],
            freeTextOne: [undefined],
            freeTextTwo: [undefined],
            freeTextThree: [undefined],
            freeTextFour: [undefined],
            freeTextFive: [undefined],
            freeTextSix: [undefined],
            freeTextSeven: [undefined],
            freeTextEight: [undefined],
            freeTextNine: [undefined],
            freeTextTen: [undefined],
            freeTextEleven: [undefined],
            freeTextTwelve: [undefined],
            freeTextThirteen: [undefined],
            freeTextFourteen: [undefined],
            freeTextFifteen: [undefined],
            freeTextSixteen: [undefined],
        });
    }

}
