export enum LoanFlag {
  ZERO_PROPOSAL_AMOUNT,
  INSURANCE_EXPIRY,
  INSUFFICIENT_SHARE_AMOUNT,
  COMPANY_VAT_PAN_EXPIRY,
  EMPTY_COMPANY_VAT_PAN_EXPIRY,
  INSUFFICIENT_Fixed_AMOUNT,
  INSUFFICIENT_VEHICLE_AMOUNT
}
